- hosts: gateway
  tasks:
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'

    - name: install nginx
      apt: name=nginx

    - name: Remove default site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent