- hosts: web
  tasks:
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'

    - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add apt repo for nodesource
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main'
        update_cache: yes

    - name: install nodejs
      apt: name=nodejs

    - name: install PM2
      npm:
        name: pm2
        global: yes
