- hosts: web
  tasks:

  - name: Copy build artifacts
    copy:
      src: ../blog-app/dist
      dest: /var/www/joelj.ca-{{ slot }}

  - name: Start PM2 process
    shell:
      chdir: /var/www/joelj.ca-{{ slot }}
      cmd: "pm2 delete joeljca{{ slot }} || PORT={{ slot_port }} pm2 start /var/www/joelj.ca-{{ slot }}/dist/blog-app/server/main.js --name joeljca{{ slot }}"