- hosts: web
  tasks:

  - name: Copy build artifacts
    copy:
      src: ../ngx-joeljca-blogapp-2/dist
      dest: /var/www/joelj.ca-{{ slot }}
      
  - name: Start PM2 process
    shell:
      chdir: /var/www/joelj.ca-{{ slot }}
      cmd: "(pm2 delete joeljca{{ slot }} || true) && APPLICATIONINSIGHTS_CONNECTION_STRING='{{ node_insights_connection_string }}' PORT={{ slot_port }} pm2 start /var/www/joelj.ca-{{ slot }}/dist/blogapp/server/main.js --name joeljca{{ slot }} && pm2 save"