name: Configure target hosts and deploy app to idle slot
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-linode:
    environment: LinodeWorld1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Write environment to global variables
      shell: bash
      run: |
        echo JJ_AZ_APP_ID=${{ vars.JJ_AZ_APP_ID }} >> "$GITHUB_ENV"
        echo JJ_AZ_SECRET=${{ secrets.JJ_AZ_SECRET }} >> "$GITHUB_ENV"
        echo JJ_AZ_TENANT_ID=${{ vars.JJ_AZ_TENANT_ID }} >> "$GITHUB_ENV"
    - name: (Sanity) echo back environment
      shell: pwsh
      run: Write-Host $($Env:JJ_AZ_SECRET.length -gt 0) $Env:JJ_AZ_APP_ID $Env:JJ_AZ_TENANT_ID
    - name: Install AZ PS module
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name Az -Repository PSGallery -Force
    - name: Connect Azure account
      shell: pwsh
      run: |
        ./cicd/PS-Connect-Az-Account.ps1
    - name: Do it live!
      working-directory: .
      shell: pwsh
      run: |
        mkdir tmp
        ./cicd/PS-Deploy-Main.ps1