# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - joeljca

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  deploy-environment-v3:
    environment: 'production3'
    name: Deploy app service Azure infrastructure
    runs-on: ubuntu-latest
    env:
      AZURE_RESOURCEGROUP_NAME: joeljca-v3
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./infrastructure/environment-v3/environment.bicep

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Set server info
        run: ./infrastructure/environment-v3/set-server-info.sh "App Service" '${{github.sha}}'
        shell: bash
      
      - name: Build SPA
        working-directory: ./blog-app
        run: |
          npm install
          npm run build:server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: blog-app
          path: ./blog-app

  deploy-to-v3:
    runs-on: ubuntu-latest
    needs: [build, deploy-environment-v3]
    environment:
      name: 'production3'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: blog-server

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wapp-joeljca'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .